basePath: /api/v1
definitions:
  dto.BenefitInfo:
    properties:
      confirmation_subjects:
        items:
          $ref: '#/definitions/dto.ConfirmSubjectResp'
        type: array
      full_score_subjects:
        items:
          type: string
        type: array
      is_bvi:
        type: boolean
      min_class:
        type: integer
      min_diploma_level:
        type: integer
    type: object
  dto.ConfirmSubjectResp:
    properties:
      score:
        type: integer
      subject:
        type: string
    type: object
  dto.FacultyProgramTree:
    properties:
      faculty_id:
        type: integer
      name:
        type: string
      programs:
        items:
          $ref: '#/definitions/dto.ProgramShortResponse'
        type: array
    type: object
  dto.FieldShortInfo:
    description: Краткая информация о направлении подготовки.
    properties:
      code:
        description: Код направления
        example: 01.03.01
        type: string
      degree:
        description: Уровень образования
        example: Бакалавриат
        type: string
      field_id:
        description: ID направления подготовки
        example: 1
        type: integer
      name:
        description: Название направления
        example: Математика
        type: string
    type: object
  dto.GroupProgramTree:
    properties:
      code:
        type: string
      group_id:
        type: integer
      name:
        type: string
      programs:
        items:
          $ref: '#/definitions/dto.ProgramShortResponse'
        type: array
    type: object
  dto.GroupResponse:
    description: Группа направлений подготовки с их параметрами.
    properties:
      code:
        description: Код группы
        example: 01.00.00
        type: string
      fields:
        description: Список направлений в группе
        items:
          $ref: '#/definitions/dto.FieldShortInfo'
        type: array
      name:
        description: Название группы
        example: Математические науки
        type: string
    type: object
  dto.OlympiadBenefitInfo:
    properties:
      level:
        type: integer
      name:
        type: string
      olympiad_id:
        type: integer
      profile:
        type: string
    type: object
  dto.OlympiadBenefitTree:
    properties:
      benefits:
        items:
          $ref: '#/definitions/dto.BenefitInfo'
        type: array
      olympiad:
        $ref: '#/definitions/dto.OlympiadBenefitInfo'
    type: object
  dto.OlympiadShortResponse:
    properties:
      level:
        description: Уровень олимпиады
        example: 1
        type: integer
      like:
        description: Лайкнута ли олимпиада пользователем
        example: true
        type: boolean
      name:
        description: Название олимпиады
        example: Олимпиада Росатом по математике
        type: string
      olympiad_id:
        description: ID олимпиады
        example: 123
        type: integer
      profile:
        description: Профиль олимпиады
        example: физика
        type: string
    type: object
  dto.ProgramBenefitInfo:
    properties:
      field:
        type: string
      name:
        type: string
      program_id:
        type: integer
      university:
        type: string
    type: object
  dto.ProgramBenefitTree:
    properties:
      benefits:
        items:
          $ref: '#/definitions/dto.BenefitInfo'
        type: array
      program:
        $ref: '#/definitions/dto.ProgramBenefitInfo'
    type: object
  dto.ProgramShortResponse:
    properties:
      budget_places:
        type: integer
      cost:
        type: integer
      field:
        type: string
      like:
        type: boolean
      name:
        type: string
      optional_subjects:
        items:
          type: string
        type: array
      paid_places:
        type: integer
      program_id:
        type: integer
      required_subjects:
        items:
          type: string
        type: array
    type: object
  dto.UniversityShortResponse:
    description: Ответ API с краткими сведениями об университете.
    properties:
      like:
        description: Лайкнут ли университет пользователем
        example: true
        type: boolean
      logo:
        description: URL логотипа
        example: https://example.com/logo.png
        type: string
      name:
        description: Полное название
        example: Московский государственный университет
        type: string
      region:
        description: Название региона
        example: Москва
        type: string
      short_name:
        description: Краткое название
        example: МГУ
        type: string
      university_id:
        description: ID университета
        example: 123
        type: integer
    type: object
  errs.AppError:
    description: Структура ошибки, возвращаемая API в случае неудачного запроса.
    properties:
      code:
        description: HTTP-код ошибки
        type: integer
      details:
        additionalProperties: true
        description: Дополнительные сведения об ошибке (если есть)
        type: object
      message:
        description: Сообщение об ошибке
        type: string
      type:
        description: Тип ошибки
        type: string
    type: object
info:
  contact:
    email: olympguide@mail.ru
    name: Support Team
  description: Это API для продажи олимпгайда за 30 лямов
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: OlympGuide API
  version: "1.0"
paths:
  /fields:
    get:
      consumes:
      - application/json
      description: Возвращает список групп и их направлений с возможностью фильтрации
        по уровню образования и поиску.
      parameters:
      - collectionFormat: csv
        description: Уровень образования
        in: query
        items:
          type: string
        name: degree
        type: array
      - description: Поиск по названию или коду (например, 'Математика' или '01.03.04')
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список групп и их направлений
          schema:
            items:
              $ref: '#/definitions/dto.GroupResponse'
            type: array
        "400":
          description: Некорректные параметры запроса
          schema:
            $ref: '#/definitions/errs.AppError'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/errs.AppError'
      summary: Получение всех направлений подготовки
      tags:
      - Группы с направлениями
  /olympiads:
    get:
      consumes:
      - application/json
      description: Возвращает список олимпиад с фильтрацией по уровню, профилю и поисковому
        запросу. Также поддерживается сортировка.
      parameters:
      - collectionFormat: multi
        description: Фильтр по уровням (можно передавать несколько значений)
        in: query
        items:
          type: string
        name: level
        type: array
      - collectionFormat: multi
        description: Фильтр по профилям (можно передавать несколько значений)
        in: query
        items:
          type: string
        name: profile
        type: array
      - description: Поисковый запрос по названию олимпиады
        in: query
        name: search
        type: string
      - description: Поле для сортировки (level, profile, name). По умолчанию сортируется
          по убыванию популярности
        in: query
        name: sort
        type: string
      - description: Порядок сортировки (asc, desc). По умолчанию asc, если указан
          `sort`
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список олимпиад
          schema:
            items:
              $ref: '#/definitions/dto.OlympiadShortResponse'
            type: array
        "400":
          description: Некорректные параметры запроса
          schema:
            $ref: '#/definitions/errs.AppError'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/errs.AppError'
      summary: Получение список олимпиад
      tags:
      - Олимпиады
  /olympiads/{id}/benefits:
    get:
      consumes:
      - application/json
      description: |-
        Возвращает список льгот по программам для указанной олимпиады.
        Поддерживаются фильтры по направлениям, признаку BVI, минимальному уровню диплома, минимальному классу, а также поиск и сортировка.
        льготы сгруппированы по программам, сортировка внутри программы: сначала БВИ, сначала 1 степень.
      parameters:
      - description: Идентификатор олимпиады
        in: path
        name: id
        required: true
        type: string
      - collectionFormat: csv
        description: Фильтр по кодам направлений (01.03.04)
        in: query
        items:
          type: string
        name: field
        type: array
      - collectionFormat: csv
        description: Фильтр по BVI
        in: query
        items:
          type: boolean
        name: is_bvi
        type: array
      - collectionFormat: csv
        description: Фильтр по минимальному уровню диплома (1, 2, 3)
        in: query
        items:
          type: integer
        name: min_diploma_level
        type: array
      - collectionFormat: csv
        description: Фильтр по минимальному классу (9, 10, 11)
        in: query
        items:
          type: integer
        name: min_class
        type: array
      - description: Поиск по названию программы и названию университета
        in: query
        name: search
        type: string
      - description: Поле сортировки программ (field - по коду, university - по популярности
          университета), по умолчанию по убыванию популярности программы.
        in: query
        name: sort
        type: string
      - description: Порядок сортировки (asc или desc)
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список льгот, сгруппированных по программам
          schema:
            items:
              $ref: '#/definitions/dto.ProgramBenefitTree'
            type: array
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/errs.AppError'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/errs.AppError'
      summary: Получить льготы по олимпиаде
      tags:
      - Льготы по олимпиаде
  /programs/{id}/benefits:
    get:
      consumes:
      - application/json
      description: |-
        Возвращает список льгот по олимпиадам для указанной образовательной программы.
        Поддерживаются фильтры по уровням олимпиады, профилям олимпиады, признаку BVI, минимальному уровню диплома,
        минимальному классу, а также поиск и сортировка. Льготы сгруппированы по олимпиадам, сортировка внутри программы: сначала БВИ, сначала 1 степень.
      parameters:
      - description: Идентификатор программы
        in: path
        name: id
        required: true
        type: string
      - collectionFormat: csv
        description: Фильтр по уровням олимпиады (1, 2, 3)
        in: query
        items:
          type: string
        name: level
        type: array
      - collectionFormat: csv
        description: Фильтр по профилям (Математика)
        in: query
        items:
          type: string
        name: profile
        type: array
      - collectionFormat: csv
        description: Фильтр по BVI
        in: query
        items:
          type: boolean
        name: is_bvi
        type: array
      - collectionFormat: csv
        description: Фильтр по минимальному уровню диплома (1, 2, 3)
        in: query
        items:
          type: integer
        name: min_diploma_level
        type: array
      - collectionFormat: csv
        description: Фильтр по минимальному классу (9, 10, 11)
        in: query
        items:
          type: integer
        name: min_class
        type: array
      - description: Поиск по названию олимпиады
        in: query
        name: search
        type: string
      - description: Поле сортировки (level - по уровню олимпиады, profile - по профилю
          олимпиады), по умолчанию по убыванию популярности олимпиады.
        in: query
        name: sort
        type: string
      - description: Порядок сортировки (asc или desc)
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список льгот, сгруппированных по олимпиадам
          schema:
            items:
              $ref: '#/definitions/dto.OlympiadBenefitTree'
            type: array
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/errs.AppError'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/errs.AppError'
      summary: Получить льготы по программе
      tags:
      - Льготы по программе
  /universities:
    get:
      consumes:
      - application/json
      description: Возвращает список университетов с учетом фильтров поиска и сортировкой
        по убыванию популярности.
      parameters:
      - collectionFormat: multi
        description: Фильтр по названию регионов
        in: query
        items:
          type: string
        name: region_id
        type: array
      - description: 'Фильтр: только университеты из региона пользователя'
        in: query
        name: from_my_region
        type: boolean
      - description: Поиск по названию или сокращенному названию
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список университетов
          schema:
            items:
              $ref: '#/definitions/dto.UniversityShortResponse'
            type: array
        "400":
          description: Некорректный запрос
          schema:
            $ref: '#/definitions/errs.AppError'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/errs.AppError'
      summary: Получение списка университетов
      tags:
      - Университеты
  /university/{id}/programs/by-faculty:
    get:
      consumes:
      - application/json
      description: Возвращает список программ, распределенных по факультетам, с возможностью
        фильтрации по предметам, уровню образования и поисковому запросу
      parameters:
      - description: ID университета
        in: path
        name: id
        required: true
        type: string
      - collectionFormat: csv
        description: 'Уровень образования (например: Бакалавриат, Магистратура)'
        in: query
        items:
          type: string
        name: degree
        type: array
      - collectionFormat: csv
        description: 'Предметы ЕГЭ (например: Русский язык, Математика)'
        in: query
        items:
          type: string
        name: subject
        type: array
      - description: 'Поиск по названию программы (например: Программная инженерия)'
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.FacultyProgramTree'
            type: array
        "400":
          description: Некорректные параметры запроса
          schema:
            $ref: '#/definitions/errs.AppError'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/errs.AppError'
      summary: Получить образовательные программы университета, сгруппированные по
        факультетам
      tags:
      - Программы в университете с группировкой
  /university/{id}/programs/by-field:
    get:
      consumes:
      - application/json
      description: Возвращает список программ, распределенных по группам направлений
        подготовки, с возможностью фильтрации по предметам, уровню образования и поисковому
        запросу
      parameters:
      - description: ID университета
        in: path
        name: id
        required: true
        type: string
      - collectionFormat: csv
        description: 'Уровень образования (например: Бакалавриат, Магистратура)'
        in: query
        items:
          type: string
        name: degree
        type: array
      - collectionFormat: csv
        description: 'Предметы ЕГЭ (например: Русский язык, Математика)'
        in: query
        items:
          type: string
        name: subject
        type: array
      - description: 'Поиск по названию программы (например: Программная инженерия)'
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.GroupProgramTree'
            type: array
        "400":
          description: Некорректные параметры запроса
          schema:
            $ref: '#/definitions/errs.AppError'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/errs.AppError'
      summary: Получить образовательные программы университета, сгруппированные по
        направлениям подготовки
      tags:
      - Программы в университете с группировкой
swagger: "2.0"
