INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (1, 'МАТЕМАТИКА И МЕХАНИКА', '01.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (2, 'КОМПЬЮТЕРНЫЕ И ИНФОРМАЦИОННЫЕ НАУКИ', '02.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (3, 'ФИЗИКА И АСТРОНОМИЯ', '03.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (4, 'ХИМИЯ', '04.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (5, 'НАУКИ О ЗЕМЛЕ', '05.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (6, 'БИОЛОГИЧЕСКИЕ НАУКИ', '06.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (7, 'АРХИТЕКТУРА', '07.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (8, 'ТЕХНИКА И ТЕХНОЛОГИИ СТРОИТЕЛЬСТВА', '08.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (9, 'ИНФОРМАТИКА И ВЫЧИСЛИТЕЛЬНАЯ ТЕХНИКА', '09.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (10, 'ИНФОРМАЦИОННАЯ БЕЗОПАСНОСТЬ', '10.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (11, 'ЭЛЕКТРОНИКА, РАДИОТЕХНИКА И СИСТЕМЫ СВЯЗИ', '11.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (12, 'ФОТОНИКА, ПРИБОРОСТРОЕНИЕ, ОПТИЧЕСКИЕ И БИОТЕХНИЧЕСКИЕ СИСТЕМЫ И ТЕХНОЛОГИИ', '12.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (13, 'ЭЛЕКТРО- И ТЕПЛОЭНЕРГЕТИКА', '13.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (14, 'ЯДЕРНАЯ ЭНЕРГЕТИКА И ТЕХНОЛОГИИ', '14.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (15, 'МАШИНОСТРОЕНИЕ', '15.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (16, 'ФИЗИКО-ТЕХНИЧЕСКИЕ НАУКИ И ТЕХНОЛОГИИ', '16.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (17, 'ОРУЖИЕ И СИСТЕМЫ ВООРУЖЕНИЯ', '17.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (18, 'ХИМИЧЕСКИЕ ТЕХНОЛОГИИ', '18.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (19, 'ПРОМЫШЛЕННАЯ ЭКОЛОГИЯ И БИОТЕХНОЛОГИИ', '19.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (20, 'ТЕХНОСФЕРНАЯ БЕЗОПАСНОСТЬ И ПРИРОДООБУСТРОЙСТВО', '20.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (21, 'ПРИКЛАДНАЯ ГЕОЛОГИЯ, ГОРНОЕ ДЕЛО, НЕФТЕГАЗОВОЕ ДЕЛО И ГЕОДЕЗИЯ', '21.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (22, 'ТЕХНОЛОГИИ МАТЕРИАЛОВ', '22.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (23, 'ТЕХНИКА И ТЕХНОЛОГИИ НАЗЕМНОГО ТРАНСПОРТА', '23.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (24, 'АВИАЦИОННАЯ И РАКЕТНО-КОСМИЧЕСКАЯ ТЕХНИКА', '24.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (25, 'АЭРОНАВИГАЦИЯ И ЭКСПЛУАТАЦИЯ АВИАЦИОННОЙ И РАКЕТНО-КОСМИЧЕСКОЙ ТЕХНИКИ', '25.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (26, 'ТЕХНИКА И ТЕХНОЛОГИИ КОРАБЛЕСТРОЕНИЯ И ВОДНОГО ТРАНСПОРТА', '26.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (27, 'УПРАВЛЕНИЕ В ТЕХНИЧЕСКИХ СИСТЕМАХ', '27.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (28, 'НАНОТЕХНОЛОГИИ И НАНОМАТЕРИАЛЫ', '28.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (29, 'ТЕХНОЛОГИИ ЛЕГКОЙ ПРОМЫШЛЕННОСТИ', '29.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (30, 'ФУНДАМЕНТАЛЬНАЯ МЕДИЦИНА', '30.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (31, 'КЛИНИЧЕСКАЯ МЕДИЦИНА', '31.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (32, 'НАУКИ О ЗДОРОВЬЕ И ПРОФИЛАКТИЧЕСКАЯ МЕДИЦИНА', '32.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (33, 'ФАРМАЦИЯ', '33.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (34, 'СЕСТРИНСКОЕ ДЕЛО', '34.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (35, 'СЕЛЬСКОЕ, ЛЕСНОЕ И РЫБНОЕ ХОЗЯЙСТВО', '35.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (36, 'ВЕТЕРИНАРИЯ И ЗООТЕХНИЯ', '36.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (37, 'ПСИХОЛОГИЧЕСКИЕ НАУКИ', '37.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (38, 'ЭКОНОМИКА И УПРАВЛЕНИЕ', '38.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (39, 'СОЦИОЛОГИЯ И СОЦИАЛЬНАЯ РАБОТА', '39.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (40, 'ЮРИСПРУДЕНЦИЯ', '40.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (41, 'ПОЛИТИЧЕСКИЕ НАУКИ И РЕГИОНОВЕДЕНИЕ', '41.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (42, 'СРЕДСТВА МАССОВОЙ ИНФОРМАЦИИ И ИНФОРМАЦИОННО-БИБЛИОТЕЧНОЕ ДЕЛО', '42.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (43, 'СЕРВИС И ТУРИЗМ', '43.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (44, 'ОБРАЗОВАНИЕ И ПЕДАГОГИЧЕСКИЕ НАУКИ', '44.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (45, 'ЯЗЫКОЗНАНИЕ И ЛИТЕРАТУРОВЕДЕНИЕ', '45.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (46, 'ИСТОРИЯ И АРХЕОЛОГИЯ', '46.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (47, 'ФИЛОСОФИЯ, ЭТИКА И РЕЛИГИОВЕДЕНИЕ', '47.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (48, 'ТЕОЛОГИЯ', '48.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (49, 'ФИЗИЧЕСКАЯ КУЛЬТУРА И СПОРТ', '49.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (50, 'ИСКУССТВОЗНАНИЕ', '50.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (51, 'КУЛЬТУРОВЕДЕНИЕ И СОЦИОКУЛЬТУРНЫЕ ПРОЕКТЫ', '51.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (52, 'СЦЕНИЧЕСКИЕ ИСКУССТВА И ЛИТЕРАТУРНОЕ ТВОРЧЕСТВО', '52.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (53, 'МУЗЫКАЛЬНОЕ ИСКУССТВО', '53.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (54, 'ИЗОБРАЗИТЕЛЬНОЕ И ПРИКЛАДНЫЕ ВИДЫ ИСКУССТВ', '54.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (55, 'ЭКРАННЫЕ ИСКУССТВА', '55.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (56, 'ВОЕННОЕ УПРАВЛЕНИЕ', '56.00.00');
INSERT INTO olympguide.group_of_fields (group_id, name, code) VALUES (57, 'ОБЕСПЕЧЕНИЕ ГОСУДАРСТВЕННОЙ БЕЗОПАСНОСТИ', '57.00.00');


INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (1, 'Математика', '01.03.01', 'Бакалавриат', 1);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (2, 'Прикладная математика и информатика', '01.03.02', 'Бакалавриат', 1);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (3, 'Механика и математическое моделирование', '01.03.03', 'Бакалавриат', 1);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (4, 'Прикладная математика', '01.03.04', 'Бакалавриат', 1);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (5, 'Статистика', '01.03.05', 'Бакалавриат', 1);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (6, 'Фундаментальные математика и механика', '01.05.01', 'Специалитет', 1);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (7, 'Математика и компьютерные науки', '02.03.01', 'Бакалавриат', 2);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (8, 'Фундаментальная информатика и информационные технологии', '02.03.02', 'Бакалавриат', 2);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (9, 'Математическое обеспечение и администрирование информационных систем', '02.03.03', 'Бакалавриат', 2);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (10, 'Прикладные математика и физика', '03.03.01', 'Бакалавриат', 3);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (11, 'Физика', '03.03.02', 'Бакалавриат', 3);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (12, 'Радиофизика', '03.03.03', 'Бакалавриат', 3);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (13, 'Астрономия', '03.05.01', 'Специалитет', 3);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (14, 'Фундаментальная и прикладная физика', '03.05.02', 'Специалитет', 3);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (15, 'Химия', '04.03.01', 'Бакалавриат', 4);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (16, 'Химия, физика и механика материалов', '04.03.02', 'Бакалавриат', 4);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (17, 'Фундаментальная и прикладная химия', '04.05.01', 'Специалитет', 4);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (18, 'Геология', '05.03.01', 'Бакалавриат', 5);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (19, 'География', '05.03.02', 'Бакалавриат', 5);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (20, 'Картография и геоинформатика', '05.03.03', 'Бакалавриат', 5);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (21, 'Гидрометеорология', '05.03.04', 'Бакалавриат', 5);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (22, 'Прикладная гидрометеорология', '05.03.05', 'Бакалавриат', 5);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (23, 'Экология и природопользование', '05.03.06', 'Бакалавриат', 5);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (24, 'Метеорология специального назначения', '05.05.01', 'Специалитет', 5);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (25, 'Военная картография', '05.05.02', 'Специалитет', 5);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (26, 'Биология', '06.03.01', 'Бакалавриат', 6);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (27, 'Почвоведение', '06.03.02', 'Бакалавриат', 6);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (28, 'Биоинженерия и биоинформатика', '06.05.01', 'Специалитет', 6);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (29, 'Фундаментальная и прикладная биология', '06.05.02', 'Специалитет', 6);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (30, 'Архитектура', '07.03.01', 'Бакалавриат', 7);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (31, 'Реконструкция и реставрация архитектурного наследия', '07.03.02', 'Бакалавриат', 7);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (32, 'Дизайн архитектурной среды', '07.03.03', 'Бакалавриат', 7);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (33, 'Градостроительство', '07.03.04', 'Бакалавриат', 7);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (34, 'Строительство', '08.03.01', 'Бакалавриат', 8);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (35, 'Строительство уникальных зданий и сооружений', '08.05.01', 'Специалитет', 8);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (36, 'Строительство, эксплуатация, восстановление и техническое прикрытие автомобильных дорог, мостов и тоннелей', '08.05.02', 'Специалитет', 8);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (37, 'Информатика и вычислительная техника', '09.03.01', 'Бакалавриат', 9);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (38, 'Информационные системы и технологии', '09.03.02', 'Бакалавриат', 9);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (39, 'Прикладная информатика', '09.03.03', 'Бакалавриат', 9);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (40, 'Программная инженерия', '09.03.04', 'Бакалавриат', 9);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (41, 'Применение и эксплуатация автоматизированных систем специального назначения', '09.05.01', 'Специалитет', 9);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (42, 'Информационная безопасность', '10.03.01', 'Бакалавриат', 10);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (43, 'Компьютерная безопасность', '10.05.01', 'Специалитет', 10);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (44, 'Информационная безопасность телекоммуникационных систем', '10.05.02', 'Специалитет', 10);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (45, 'Информационная безопасность автоматизированных систем', '10.05.03', 'Специалитет', 10);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (46, 'Информационно-аналитические системы безопасности', '10.05.04', 'Специалитет', 10);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (47, 'Безопасность информационных технологий в правоохранительной сфере', '10.05.05', 'Специалитет', 10);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (48, 'Криптография', '10.05.06', 'Специалитет', 10);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (49, 'Противодействие техническим разведкам', '10.05.07', 'Специалитет', 10);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (50, 'Радиотехника', '11.03.01', 'Бакалавриат', 11);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (51, 'Инфокоммуникационные технологии и системы связи', '11.03.02', 'Бакалавриат', 11);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (52, 'Конструирование и технология электронных средств', '11.03.03', 'Бакалавриат', 11);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (53, 'Электроника и наноэлектроника', '11.03.04', 'Бакалавриат', 11);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (54, 'Радиоэлектронные системы и комплексы', '11.05.01', 'Специалитет', 11);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (55, 'Специальные радиотехнические системы', '11.05.02', 'Специалитет', 11);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (56, 'Применение и эксплуатация средств и систем специального мониторинга', '11.05.03', 'Специалитет', 11);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (57, 'Инфокоммуникационные технологии и системы специальной связи', '11.05.04', 'Специалитет', 11);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (58, 'Приборостроение', '12.03.01', 'Бакалавриат', 12);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (59, 'Оптотехника', '12.03.02', 'Бакалавриат', 12);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (60, 'Фотоника и оптоинформатика', '12.03.03', 'Бакалавриат', 12);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (164, 'Наноматериалы', '28.03.03', 'Бакалавриат', 28);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (61, 'Биотехнические системы и технологии', '12.03.04', 'Бакалавриат', 12);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (62, 'Лазерная техника и лазерные технологии', '12.03.05', 'Бакалавриат', 12);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (63, 'Электронные и оптико-электронные приборы и системы специального назначения', '12.05.01', 'Специалитет', 12);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (64, 'Теплоэнергетика и теплотехника', '13.03.01', 'Бакалавриат', 13);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (65, 'Электроэнергетика и электротехника', '13.03.02', 'Бакалавриат', 13);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (66, 'Энергетическое машиностроение', '13.03.03', 'Бакалавриат', 13);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (67, 'Тепло- и электрообеспечение специальных технических систем и объектов', '13.05.01', 'Специалитет', 13);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (68, 'Специальные электромеханические системы', '13.05.02', 'Специалитет', 13);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (69, 'Ядерная энергетика и теплофизика', '14.03.01', 'Бакалавриат', 14);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (70, 'Ядерные физика и технологии', '14.03.02', 'Бакалавриат', 14);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (71, 'Ядерные реакторы и материалы', '14.05.01', 'Специалитет', 14);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (72, 'Атомные станции: проектирование, эксплуатация и инжиниринг', '14.05.02', 'Специалитет', 14);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (73, 'Технологии разделения изотопов и ядерное топливо', '14.05.03', 'Специалитет', 14);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (74, 'Электроника и автоматика физических установок', '14.05.04', 'Специалитет', 14);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (75, 'Машиностроение', '15.03.01', 'Бакалавриат', 15);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (76, 'Технологические машины и оборудование', '15.03.02', 'Бакалавриат', 15);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (77, 'Прикладная механика', '15.03.03', 'Бакалавриат', 15);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (78, 'Автоматизация технологических процессов и производств', '15.03.04', 'Бакалавриат', 15);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (79, 'Конструкторско-технологическое обеспечение машиностроительных производств', '15.03.05', 'Бакалавриат', 15);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (80, 'Мехатроника и робототехника', '15.03.06', 'Бакалавриат', 15);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (81, 'Проектирование технологических машин и комплексов', '15.05.01', 'Специалитет', 15);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (82, 'Робототехника военного и специального назначения', '15.05.02', 'Специалитет', 15);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (83, 'Техническая физика', '16.03.01', 'Бакалавриат', 16);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (84, 'Высокотехнологические плазменные и энергетические установки', '16.03.02', 'Бакалавриат', 16);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (85, 'Холодильная, криогенная техника и системы жизнеобеспечения', '16.03.03', 'Бакалавриат', 16);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (86, 'Специальные системы жизнеобеспечения', '16.05.01', 'Специалитет', 16);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (87, 'Корабельное вооружение', '17.03.01', 'Бакалавриат', 17);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (88, 'Боеприпасы и взрыватели', '17.05.01', 'Специалитет', 17);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (89, 'Стрелково-пушечное, артиллерийское и ракетное оружие', '17.05.02', 'Специалитет', 17);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (90, 'Проектирование, производство и испытание корабельного вооружения и информационно-управляющих систем', '17.05.03', 'Специалитет', 17);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (91, 'Технологии веществ и материалов в вооружении и военной технике', '17.05.04', 'Специалитет', 17);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (92, 'Химическая технология', '18.03.01', 'Бакалавриат', 18);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (93, 'Энерго- и ресурсосберегающие процессы в химической технологии, нефтехимии и биотехнологии', '18.03.02', 'Бакалавриат', 18);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (94, 'Химическая технология энергонасыщенных материалов и изделий', '18.05.01', 'Специалитет', 18);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (95, 'Химическая технология материалов современной энергетики', '18.05.02', 'Специалитет', 18);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (96, 'Биотехнология', '19.03.01', 'Бакалавриат', 19);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (97, 'Продукты питания из растительного сырья', '19.03.02', 'Бакалавриат', 19);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (98, 'Продукты питания животного происхождения', '19.03.03', 'Бакалавриат', 19);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (99, 'Технология продукции и организация общественного питания', '19.03.04', 'Бакалавриат', 19);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (100, 'Техносферная безопасность', '20.03.01', 'Бакалавриат', 20);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (101, 'Природообустройство и водопользование', '20.03.02', 'Бакалавриат', 20);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (102, 'Пожарная безопасность', '20.05.01', 'Специалитет', 20);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (103, 'Нефтегазовое дело', '21.03.01', 'Бакалавриат', 21);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (104, 'Землеустройство и кадастры', '21.03.02', 'Бакалавриат', 21);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (105, 'Геодезия и дистанционное зондирование', '21.03.03', 'Бакалавриат', 21);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (106, 'Прикладная геодезия', '21.05.01', 'Специалитет', 21);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (107, 'Прикладная геология', '21.05.02', 'Специалитет', 21);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (108, 'Технология геологической разведки', '21.05.03', 'Специалитет', 21);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (109, 'Горное дело', '21.05.04', 'Специалитет', 21);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (110, 'Физические процессы горного или нефтегазового производства', '21.05.05', 'Специалитет', 21);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (111, 'Нефтегазовые техника и технологии', '21.05.06', 'Специалитет', 21);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (112, 'Материаловедение и технологии материалов', '22.03.01', 'Бакалавриат', 22);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (113, 'Металлургия', '22.03.02', 'Бакалавриат', 22);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (114, 'Технология транспортных процессов', '23.03.01', 'Бакалавриат', 23);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (115, 'Наземные транспортно-технологические комплексы', '23.03.02', 'Бакалавриат', 23);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (116, 'Эксплуатация транспортно-технологических машин и комплексов', '23.03.03', 'Бакалавриат', 23);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (117, 'Наземные транспортно-технологические средства', '23.05.01', 'Специалитет', 23);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (118, 'Транспортные средства специального назначения', '23.05.02', 'Специалитет', 23);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (119, 'Подвижной состав железных дорог', '23.05.03', 'Специалитет', 23);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (120, 'Эксплуатация железных дорог', '23.05.04', 'Специалитет', 23);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (121, 'Системы обеспечения движения поездов', '23.05.05', 'Специалитет', 23);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (122, 'Строительство железных дорог, мостов и транспортных тоннелей', '23.05.06', 'Специалитет', 23);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (123, 'Ракетные комплексы и космонавтика', '24.03.01', 'Бакалавриат', 24);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (124, 'Системы управления движением и навигация', '24.03.02', 'Бакалавриат', 24);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (125, 'Баллистика и гидроаэродинамика', '24.03.03', 'Бакалавриат', 24);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (126, 'Авиастроение', '24.03.04', 'Бакалавриат', 24);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (127, 'Двигатели летательных аппаратов', '24.03.05', 'Бакалавриат', 24);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (128, 'Проектирование, производство и эксплуатация ракет и ракетно-космических комплексов', '24.05.01', 'Специалитет', 24);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (129, 'Проектирование авиационных и ракетных двигателей', '24.05.02', 'Специалитет', 24);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (130, 'Испытание летательных аппаратов', '24.05.03', 'Специалитет', 24);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (131, 'Навигационно-баллистическое обеспечение применения космической техники', '24.05.04', 'Специалитет', 24);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (132, 'Интегрированные системы летательных аппаратов', '24.05.05', 'Специалитет', 24);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (133, 'Системы управления летательными аппаратами', '24.05.06', 'Специалитет', 24);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (134, 'Самолето- и вертолетостроение', '24.05.07', 'Специалитет', 24);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (135, 'Техническая эксплуатация летательных аппаратов и двигателей', '25.03.01', 'Бакалавриат', 25);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (136, 'Техническая эксплуатация авиационных электросистем и пилотажно-навигационных комплексов', '25.03.02', 'Бакалавриат', 25);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (137, 'Аэронавигация', '25.03.03', 'Бакалавриат', 25);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (138, 'Эксплуатация аэропортов и обеспечение полетов воздушных судов', '25.03.04', 'Бакалавриат', 25);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (139, 'Техническая эксплуатация и восстановление боевых летательных аппаратов и двигателей', '25.05.01', 'Специалитет', 25);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (140, 'Техническая эксплуатация и восстановление электросистем и пилотажно-навигационных комплексов боевых летательных аппаратов', '25.05.02', 'Специалитет', 25);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (141, 'Техническая эксплуатация транспортного радиооборудования', '25.05.03', 'Специалитет', 25);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (142, 'Летная эксплуатация и применение авиационных комплексов', '25.05.04', 'Специалитет', 25);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (143, 'Эксплуатация воздушных судов и организация воздушного движения', '25.05.05', 'Специалитет', 25);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (144, 'Управление водным транспортом и гидрографическое обеспечение судоходства', '26.03.01', 'Бакалавриат', 26);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (145, 'Кораблестроение, океанотехника и системотехника объектов морской инфраструктуры', '26.03.02', 'Бакалавриат', 26);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (146, 'Водные пути, порты и гидротехнические сооружения', '26.03.03', 'Бакалавриат', 26);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (147, 'Инженерно-экономическое обеспечение технологий и бизнес-процессов водного транспорта', '26.03.04', 'Бакалавриат', 26);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (148, 'Проектирование и постройка кораблей, судов и объектов океанотехники', '26.05.01', 'Специалитет', 26);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (149, 'Проектирование, изготовление и ремонт энергетических установок и систем автоматизации кораблей и судов', '26.05.02', 'Специалитет', 26);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (150, 'Строительство, ремонт и поисково-спасательное обеспечение надводных кораблей и подводных лодок', '26.05.03', 'Специалитет', 26);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (151, 'Применение и эксплуатация технических систем надводных кораблей и подводных лодок', '26.05.04', 'Специалитет', 26);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (152, 'Судовождение', '26.05.05', 'Специалитет', 26);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (153, 'Эксплуатация судовых энергетических установок', '26.05.06', 'Специалитет', 26);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (154, 'Эксплуатация судового электрооборудования и средств автоматики', '26.05.07', 'Специалитет', 26);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (155, 'Стандартизация и метрология', '27.03.01', 'Бакалавриат', 27);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (156, 'Управление качеством', '27.03.02', 'Бакалавриат', 27);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (157, 'Системный анализ и управление', '27.03.03', 'Бакалавриат', 27);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (158, 'Управление в технических системах', '27.03.04', 'Бакалавриат', 27);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (159, 'Инноватика', '27.03.05', 'Бакалавриат', 27);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (160, 'Специальные организационно-технические системы', '27.05.01', 'Специалитет', 27);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (161, 'Метрологическое обеспечение вооружения и военной техники', '27.05.02', 'Специалитет', 27);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (162, 'Нанотехнологии и микросистемная техника', '28.03.01', 'Бакалавриат', 28);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (163, 'Наноинженерия', '28.03.02', 'Бакалавриат', 28);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (165, 'Технология изделий легкой промышленности', '29.03.01', 'Бакалавриат', 29);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (166, 'Технологии и проектирование текстильных изделий', '29.03.02', 'Бакалавриат', 29);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (167, 'Технология полиграфического и упаковочного производства', '29.03.03', 'Бакалавриат', 29);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (168, 'Технология художественной обработки материалов', '29.03.04', 'Бакалавриат', 29);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (169, 'Конструирование изделий легкой промышленности', '29.03.05', 'Бакалавриат', 29);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (170, 'Медицинская биохимия', '30.05.01', 'Специалитет', 30);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (171, 'Медицинская биофизика', '30.05.02', 'Специалитет', 30);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (172, 'Медицинская кибернетика', '30.05.03', 'Специалитет', 30);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (173, 'Лечебное дело', '31.05.01', 'Специалитет', 31);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (174, 'Педиатрия', '31.05.02', 'Специалитет', 31);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (175, 'Стоматология', '31.05.03', 'Специалитет', 31);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (176, 'Остеопатия', '31.05.04', 'Специалитет', 31);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (177, 'Медико-профилактическое дело', '32.05.01', 'Специалитет', 32);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (178, 'Фармация', '33.05.01', 'Специалитет', 33);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (179, 'Сестринское дело', '34.03.01', 'Специалитет', 34);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (180, 'Лесное дело', '35.03.01', 'Бакалавриат', 35);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (181, 'Технология лесозаготовительных и деревоперерабатывающих производств', '35.03.02', 'Бакалавриат', 35);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (182, 'Агрохимия и агропочвоведение', '35.03.03', 'Бакалавриат', 35);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (183, 'Агрономия', '35.03.04', 'Бакалавриат', 35);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (184, 'Садоводство', '35.03.05', 'Бакалавриат', 35);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (185, 'Агроинженерия', '35.03.06', 'Бакалавриат', 35);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (186, 'Технология производства и переработки сельскохозяйственной продукции', '35.03.07', 'Бакалавриат', 35);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (187, 'Водные биоресурсы и аквакультура', '35.03.08', 'Бакалавриат', 35);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (188, 'Промышленное рыболовство', '35.03.09', 'Бакалавриат', 35);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (189, 'Ландшафтная архитектура', '35.03.10', 'Бакалавриат', 35);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (190, 'Гидромелиорация', '35.03.11', 'Бакалавриат', 35);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (191, 'Ветеринарно-санитарная экспертиза', '36.03.01', 'Бакалавриат', 36);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (192, 'Зоотехния', '36.03.02', 'Бакалавриат', 36);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (193, 'Ветеринария', '36.05.01', 'Специалитет', 36);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (194, 'Психология', '37.03.01', 'Бакалавриат', 37);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (195, 'Конфликтология', '37.03.02', 'Бакалавриат', 37);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (196, 'Клиническая психология', '37.05.01', 'Специалитет', 37);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (197, 'Психология служебной деятельности', '37.05.02', 'Специалитет', 37);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (198, 'Экономика', '38.03.01', 'Бакалавриат', 38);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (199, 'Менеджмент', '38.03.02', 'Бакалавриат', 38);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (200, 'Управление персоналом', '38.03.03', 'Бакалавриат', 38);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (201, 'Государственное и муниципальное управление', '38.03.04', 'Бакалавриат', 38);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (202, 'Бизнес-информатика', '38.03.05', 'Бакалавриат', 38);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (203, 'Торговое дело', '38.03.06', 'Бакалавриат', 38);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (204, 'Товароведение', '38.03.07', 'Бакалавриат', 38);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (205, 'Жилищное хозяйство и коммунальная инфраструктура', '38.03.10', 'Бакалавриат', 38);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (206, 'Экономическая безопасность', '38.05.01', 'Специалитет', 38);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (207, 'Таможенное дело', '38.05.02', 'Специалитет', 38);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (208, 'Социология', '39.03.01', 'Бакалавриат', 39);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (209, 'Социальная работа', '39.03.02', 'Бакалавриат', 39);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (210, 'Организация работы с молодежью', '39.03.03', 'Бакалавриат', 39);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (211, 'Юриспруденция', '40.03.01', 'Бакалавриат', 40);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (212, 'Обеспечение законности и правопорядка', '40.03.02', 'Бакалавриат', 40);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (213, 'Правовое обеспечение национальной безопасности', '40.05.01', 'Специалитет', 40);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (214, 'Правоохранительная деятельность', '40.05.02', 'Специалитет', 40);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (215, 'Судебная экспертиза', '40.05.03', 'Специалитет', 40);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (216, 'Судебная и прокурорская деятельность', '40.05.04', 'Специалитет', 40);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (217, 'Зарубежное регионоведение', '41.03.01', 'Бакалавриат', 41);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (218, 'Регионоведение России', '41.03.02', 'Бакалавриат', 41);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (219, 'Востоковедение и африканистика', '41.03.03', 'Бакалавриат', 41);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (220, 'Политология', '41.03.04', 'Бакалавриат', 41);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (221, 'Международные отношения', '41.03.05', 'Бакалавриат', 41);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (222, 'Публичная политика и социальные науки', '41.03.06', 'Бакалавриат', 41);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (223, 'Реклама и связи с общественностью', '42.03.01', 'Бакалавриат', 42);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (224, 'Журналистика', '42.03.02', 'Бакалавриат', 42);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (225, 'Издательское дело', '42.03.03', 'Бакалавриат', 42);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (226, 'Телевидение', '42.03.04', 'Бакалавриат', 42);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (227, 'Медиакоммуникации', '42.03.05', 'Бакалавриат', 42);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (228, 'Сервис', '43.03.01', 'Бакалавриат', 43);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (229, 'Туризм', '43.03.02', 'Бакалавриат', 43);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (230, 'Гостиничное дело', '43.03.03', 'Бакалавриат', 43);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (231, 'Педагогическое образование', '44.03.01', 'Бакалавриат', 44);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (232, 'Психолого-педагогическое образование', '44.03.02', 'Бакалавриат', 44);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (297, 'Скульптура', '54.05.04', 'Специалитет', 54);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (233, 'Специальное (дефектологическое) образование', '44.03.03', 'Бакалавриат', 44);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (234, 'Профессиональное обучение (по отраслям)', '44.03.04', 'Бакалавриат', 44);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (235, 'Педагогическое образование (с двумя профилями подготовки)', '44.03.05', 'Бакалавриат', 44);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (236, 'Педагогика и психология девиантного поведения', '44.05.01', 'Специалитет', 44);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (237, 'Филология', '45.03.01', 'Бакалавриат', 45);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (238, 'Лингвистика', '45.03.02', 'Бакалавриат', 45);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (239, 'Фундаментальная и прикладная лингвистика', '45.03.03', 'Бакалавриат', 45);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (240, 'Интеллектуальные системы в гуманитарной сфере', '45.03.04', 'Бакалавриат', 45);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (241, 'Перевод и переводоведение', '45.05.01', 'Специалитет', 45);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (242, 'История', '46.03.01', 'Бакалавриат', 46);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (243, 'Документоведение и архивоведение', '46.03.02', 'Бакалавриат', 46);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (244, 'Антропология и этнология', '46.03.03', 'Бакалавриат', 46);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (245, 'Археология', '46.03.04', 'Бакалавриат', 46);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (246, 'Философия', '47.03.01', 'Бакалавриат', 47);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (247, 'Прикладная этика', '47.03.02', 'Бакалавриат', 47);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (248, 'Религиоведение', '47.03.03', 'Бакалавриат', 47);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (249, 'Теология', '48.03.01', 'Бакалавриат', 48);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (250, 'Физическая культура', '49.03.01', 'Бакалавриат', 49);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (251, 'Физическая культура для лиц с отклонениями в состоянии здоровья (адаптивная физическая культура)', '49.03.02', 'Бакалавриат', 49);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (252, 'Рекреация и спортивно-оздоровительный туризм', '49.03.03', 'Бакалавриат', 49);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (253, 'Спорт', '49.03.04', 'Специалитет', 49);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (254, 'Искусства и гуманитарные науки', '50.03.01', 'Бакалавриат', 50);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (255, 'Изящные искусства', '50.03.02', 'Бакалавриат', 50);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (256, 'История искусств', '50.03.03', 'Бакалавриат', 50);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (257, 'Теория и история искусств', '50.03.04', 'Бакалавриат', 50);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (258, 'Культурология', '51.03.01', 'Бакалавриат', 51);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (259, 'Народная художественная культура', '51.03.02', 'Бакалавриат', 51);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (260, 'Социально-культурная деятельность', '51.03.03', 'Бакалавриат', 51);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (261, 'Музеология и охрана объектов культурного и природного наследия', '51.03.04', 'Бакалавриат', 51);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (262, 'Режиссура театрализованных представлений и праздников', '51.03.05', 'Бакалавриат', 51);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (263, 'Библиотечно-информационная деятельность', '51.03.06', 'Бакалавриат', 51);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (264, 'Звукорежиссура культурно-массовых представлений и концертных программ', '51.05.01', 'Специалитет', 51);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (265, 'Хореографическое искусство', '52.03.01', 'Бакалавриат', 52);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (266, 'Хореографическое исполнительство', '52.03.02', 'Бакалавриат', 52);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (267, 'Цирковое искусство', '52.03.03', 'Бакалавриат', 52);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (268, 'Технология художественного оформления спектакля', '52.03.04', 'Бакалавриат', 52);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (269, 'Театроведение', '52.03.05', 'Бакалавриат', 52);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (270, 'Драматургия', '52.03.06', 'Бакалавриат', 52);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (271, 'Актерское искусство', '52.05.01', 'Специалитет', 52);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (272, 'Режиссура театра', '52.05.02', 'Специалитет', 52);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (273, 'Сценография', '52.05.03', 'Специалитет', 52);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (274, 'Литературное творчество', '52.05.04', 'Специалитет', 52);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (275, 'Актерское искусство в музыкальном театре', '52.05.05', 'Специалитет', 52);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (276, 'Музыкальное искусство эстрады', '53.03.01', 'Бакалавриат', 53);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (277, 'Музыкально-инструментальное искусство', '53.03.02', 'Бакалавриат', 53);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (278, 'Вокальное искусство', '53.03.03', 'Бакалавриат', 53);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (279, 'Искусство народного пения', '53.03.04', 'Бакалавриат', 53);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (280, 'Дирижирование', '53.03.05', 'Бакалавриат', 53);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (281, 'Музыкознание и музыкально-прикладное искусство', '53.03.06', 'Бакалавриат', 53);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (282, 'Искусство концертного исполнительства', '53.05.01', 'Специалитет', 53);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (283, 'Художественное руководство оперно-симфоническим оркестром и академическим хором', '53.05.02', 'Специалитет', 53);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (284, 'Музыкальная звукорежиссура', '53.05.03', 'Специалитет', 53);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (285, 'Музыкально-театральное искусство', '53.05.04', 'Специалитет', 53);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (286, 'Музыковедение', '53.05.05', 'Специалитет', 53);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (287, 'Композиция', '53.05.06', 'Специалитет', 53);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (288, 'Дирижирование военным духовым оркестром', '53.05.07', 'Специалитет', 53);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (289, 'Дизайн', '54.03.01', 'Бакалавриат', 54);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (290, 'Декоративно-прикладное искусство и народные промыслы', '54.03.02', 'Бакалавриат', 54);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (291, 'Искусство костюма и текстиля', '54.03.03', 'Бакалавриат', 54);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (292, 'Реставрация', '54.03.04', 'Бакалавриат', 54);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (293, 'Традиционное прикладное искусство', '54.03.05', 'Бакалавриат', 54);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (294, 'Монументально-декоративное искусство', '54.05.01', 'Специалитет', 54);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (295, 'Живопись', '54.05.02', 'Специалитет', 54);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (296, 'Графика', '54.05.03', 'Специалитет', 54);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (298, 'Живопись и изящные искусства', '54.05.05', 'Специалитет', 54);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (299, 'Режиссура кино и телевидения', '55.05.01', 'Специалитет', 55);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (300, 'Звукорежиссура аудиовизуальных искусств', '55.05.02', 'Специалитет', 55);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (301, 'Кинооператорство', '55.05.03', 'Специалитет', 55);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (302, 'Продюсерство', '55.05.04', 'Специалитет', 55);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (303, 'Киноведение', '55.05.05', 'Специалитет', 55);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (304, 'Тыловое обеспечение', '56.05.01', 'Специалитет', 56);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (305, 'Радиационная, химическая и биологическая защита', '56.05.02', 'Специалитет', 56);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (306, 'Служебно-прикладная физическая подготовка', '56.05.03', 'Специалитет', 56);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (307, 'Управление персоналом (Вооруженные Силы Российской Федерации, другие войска, воинские формирования и приравненные к ним органы Российской Федерации)', '56.05.04', 'Специалитет', 56);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (308, 'Военная журналистика', '56.05.05', 'Специалитет', 56);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (309, 'Защита информации на объектах информатизации военного назначения', '56.05.06', 'Специалитет', 56);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (310, 'Строительство и эксплуатация зданий и сооружений военного и специального назначения', '56.05.07', 'Специалитет', 56);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (311, 'Военно-политическая работа', '56.05.08', 'Специалитет', 56);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (312, 'Пограничная деятельность', '57.05.01', 'Специалитет', 57);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (313, 'Государственная охрана', '57.05.02', 'Специалитет', 57);
INSERT INTO olympguide.field_of_study (field_id, name, code, degree, group_id) VALUES (314, 'Технологическое обеспечение национальной безопасности и обороны', '57.05.03', 'Специалитет', 57);
