INSERT INTO olympguide.region (region_id, name) VALUES (1, 'Республика Адыгея');
INSERT INTO olympguide.region (region_id, name) VALUES (2, 'Республика Алтай');
INSERT INTO olympguide.region (region_id, name) VALUES (3, 'Алтайский край');
INSERT INTO olympguide.region (region_id, name) VALUES (4, 'Амурская область');
INSERT INTO olympguide.region (region_id, name) VALUES (5, 'Архангельская область');
INSERT INTO olympguide.region (region_id, name) VALUES (6, 'Астраханская область');
INSERT INTO olympguide.region (region_id, name) VALUES (7, 'Республика Башкортостан');
INSERT INTO olympguide.region (region_id, name) VALUES (8, 'Белгородская область');
INSERT INTO olympguide.region (region_id, name) VALUES (9, 'Брянская область');
INSERT INTO olympguide.region (region_id, name) VALUES (10, 'Республика Бурятия');
INSERT INTO olympguide.region (region_id, name) VALUES (11, 'Владимирская область');
INSERT INTO olympguide.region (region_id, name) VALUES (12, 'Волгоградская область');
INSERT INTO olympguide.region (region_id, name) VALUES (13, 'Вологодская область');
INSERT INTO olympguide.region (region_id, name) VALUES (14, 'Воронежская область');
INSERT INTO olympguide.region (region_id, name) VALUES (15, 'Республика Дагестан');
INSERT INTO olympguide.region (region_id, name) VALUES (16, 'Донецкая Народная Республика');
INSERT INTO olympguide.region (region_id, name) VALUES (17, 'Еврейская автономная область');
INSERT INTO olympguide.region (region_id, name) VALUES (18, 'Забайкальский край');
INSERT INTO olympguide.region (region_id, name) VALUES (19, 'Запорожская область');
INSERT INTO olympguide.region (region_id, name) VALUES (20, 'Ивановская область');
INSERT INTO olympguide.region (region_id, name) VALUES (21, 'Республика Ингушетия');
INSERT INTO olympguide.region (region_id, name) VALUES (22, 'Иркутская область');
INSERT INTO olympguide.region (region_id, name) VALUES (23, 'Кабардино-Балкарская Республика');
INSERT INTO olympguide.region (region_id, name) VALUES (24, 'Калининградская область');
INSERT INTO olympguide.region (region_id, name) VALUES (25, 'Республика Калмыкия');
INSERT INTO olympguide.region (region_id, name) VALUES (26, 'Калужская область');
INSERT INTO olympguide.region (region_id, name) VALUES (27, 'Камчатский край');
INSERT INTO olympguide.region (region_id, name) VALUES (28, 'Карачаево-Черкесская Республика');
INSERT INTO olympguide.region (region_id, name) VALUES (29, 'Республика Карелия');
INSERT INTO olympguide.region (region_id, name) VALUES (30, 'Кемеровская область – Кузбасс');
INSERT INTO olympguide.region (region_id, name) VALUES (31, 'Кировская область');
INSERT INTO olympguide.region (region_id, name) VALUES (32, 'Республика Коми');
INSERT INTO olympguide.region (region_id, name) VALUES (33, 'Костромская область');
INSERT INTO olympguide.region (region_id, name) VALUES (34, 'Краснодарский край');
INSERT INTO olympguide.region (region_id, name) VALUES (35, 'Красноярский край');
INSERT INTO olympguide.region (region_id, name) VALUES (36, 'Курганская область');
INSERT INTO olympguide.region (region_id, name) VALUES (37, 'Курская область');
INSERT INTO olympguide.region (region_id, name) VALUES (38, 'Ленинградская область');
INSERT INTO olympguide.region (region_id, name) VALUES (39, 'Липецкая область');
INSERT INTO olympguide.region (region_id, name) VALUES (40, 'Луганская Народная Республика');
INSERT INTO olympguide.region (region_id, name) VALUES (41, 'Магаданская область');
INSERT INTO olympguide.region (region_id, name) VALUES (42, 'Республика Марий Эл');
INSERT INTO olympguide.region (region_id, name) VALUES (43, 'Республика Мордовия');
INSERT INTO olympguide.region (region_id, name) VALUES (44, 'Москва и Московская область');
INSERT INTO olympguide.region (region_id, name) VALUES (45, 'Мурманская область');
INSERT INTO olympguide.region (region_id, name) VALUES (46, 'Ненецкий автономный округ');
INSERT INTO olympguide.region (region_id, name) VALUES (47, 'Нижегородская область');
INSERT INTO olympguide.region (region_id, name) VALUES (48, 'Новгородская область');
INSERT INTO olympguide.region (region_id, name) VALUES (49, 'Новосибирская область');
INSERT INTO olympguide.region (region_id, name) VALUES (50, 'Омская область');
INSERT INTO olympguide.region (region_id, name) VALUES (51, 'Оренбургская область');
INSERT INTO olympguide.region (region_id, name) VALUES (52, 'Орловская область');
INSERT INTO olympguide.region (region_id, name) VALUES (53, 'Пензенская область');
INSERT INTO olympguide.region (region_id, name) VALUES (54, 'Пермский край');
INSERT INTO olympguide.region (region_id, name) VALUES (55, 'Приморский край');
INSERT INTO olympguide.region (region_id, name) VALUES (56, 'Псковская область');
INSERT INTO olympguide.region (region_id, name) VALUES (57, 'Ростовская область');
INSERT INTO olympguide.region (region_id, name) VALUES (58, 'Рязанская область');
INSERT INTO olympguide.region (region_id, name) VALUES (59, 'Самарская область');
INSERT INTO olympguide.region (region_id, name) VALUES (60, 'Санкт-Петербург и Ленинградская область');
INSERT INTO olympguide.region (region_id, name) VALUES (61, 'Саратовская область');
INSERT INTO olympguide.region (region_id, name) VALUES (62, 'Республика Саха (Якутия)');
INSERT INTO olympguide.region (region_id, name) VALUES (63, 'Сахалинская область');
INSERT INTO olympguide.region (region_id, name) VALUES (64, 'Свердловская область');
INSERT INTO olympguide.region (region_id, name) VALUES (65, 'Севастополь и республика Крым');
INSERT INTO olympguide.region (region_id, name) VALUES (66, 'Республика Северная Осетия — Алания');
INSERT INTO olympguide.region (region_id, name) VALUES (67, 'Смоленская область');
INSERT INTO olympguide.region (region_id, name) VALUES (68, 'Ставропольский край');
INSERT INTO olympguide.region (region_id, name) VALUES (69, 'Тамбовская область');
INSERT INTO olympguide.region (region_id, name) VALUES (70, 'Республика Татарстан');
INSERT INTO olympguide.region (region_id, name) VALUES (71, 'Тверская область');
INSERT INTO olympguide.region (region_id, name) VALUES (72, 'Томская область');
INSERT INTO olympguide.region (region_id, name) VALUES (73, 'Тульская область');
INSERT INTO olympguide.region (region_id, name) VALUES (74, 'Республика Тыва');
INSERT INTO olympguide.region (region_id, name) VALUES (75, 'Тюменская область');
INSERT INTO olympguide.region (region_id, name) VALUES (76, 'Удмуртская Республика');
INSERT INTO olympguide.region (region_id, name) VALUES (77, 'Ульяновская область');
INSERT INTO olympguide.region (region_id, name) VALUES (78, 'Хабаровский край');
INSERT INTO olympguide.region (region_id, name) VALUES (79, 'Республика Хакасия');
INSERT INTO olympguide.region (region_id, name) VALUES (80, 'Ханты-Мансийский автономный округ — Югра');
INSERT INTO olympguide.region (region_id, name) VALUES (81, 'Херсонская область');
INSERT INTO olympguide.region (region_id, name) VALUES (82, 'Челябинская область');
INSERT INTO olympguide.region (region_id, name) VALUES (83, 'Чеченская Республика');
INSERT INTO olympguide.region (region_id, name) VALUES (84, 'Чувашская Республика — Чувашия');
INSERT INTO olympguide.region (region_id, name) VALUES (85, 'Чукотский автономный округ');
INSERT INTO olympguide.region (region_id, name) VALUES (86, 'Ямало-Ненецкий автономный округ');
INSERT INTO olympguide.region (region_id, name) VALUES (87, 'Ярославская область');
