INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (1, '«Финатлон для старшеклассников» - Всероссийская олимпиада по финансовой грамотности, устойчивому развитию и защите прав потребителей финансовых услуг', null, 3, 'финансовая грамотность');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (2, '«Формула Единства»/«Третье тысячелетие»', null, 3, 'иностранный язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (3, '«Формула Единства»/«Третье тысячелетие»', null, 2, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (4, 'XVII Южно-Российская межрегиональная олимпиада школьников «Архитектура и искусство» по комплексу предметов (рисунок, живопись, композиция, черчение)', null, 1, 'рисунок, живопись, композиция, черчение');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (5, 'Всероссийская (с международным участием) олимпиада учащихся музыкальных колледжей', null, 3, 'теория и история музыки');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (6, 'Всероссийская (с международным участием) олимпиада учащихся музыкальных колледжей', null, 3, 'деревянные духовые инструменты');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (7, 'Всероссийская (с международным участием) олимпиада учащихся музыкальных колледжей', null, 3, 'инструменты народного оркестра');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (8, 'Всероссийская (с международным участием) олимпиада учащихся музыкальных колледжей', null, 3, 'музыкальная педагогика и исполнительство');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (9, 'Всероссийская (с международным участием) олимпиада учащихся музыкальных колледжей', null, 3, 'струнные инструменты');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (10, 'Всероссийская (с международным участием) олимпиада учащихся музыкальных колледжей', null, 3, 'фортепиано');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (11, 'Всероссийская (с международным участием) олимпиада учащихся музыкальных колледжей', null, 3, 'хоровое дирижирование');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (12, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 2, 'цифровые технологии в архитектуре');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (13, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 3, 'спутниковые системы');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (14, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 2, 'водные робототехнические системы');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (15, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 2, 'наносистемы и наноинженерия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (16, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 3, 'летающая робототехника');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (17, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 2, 'беспилотные авиационные системы');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (18, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 2, 'технологии беспроводной связи');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (19, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 2, 'автоматизация бизнес-процессов');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (20, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 3, 'интеллектуальные робототехнические системы');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (21, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 3, 'аэрокосмические системы');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (22, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 3, 'виртуальные миры: разработка компьютерных игр, технологии виртуальной реальности, технологии дополненной реальности');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (23, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 3, 'информационная безопасность');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (24, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 3, 'искусственный интеллект');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (25, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 3, 'большие данные и машинное обучение');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (26, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 3, 'интеллектуальные энергетические системы');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (27, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 2, 'автономные транспортные системы');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (28, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 3, 'анализ космических снимков и геопространственных данных');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (29, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 2, 'инженерные биологические системы');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (30, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 3, 'геномное редактирование');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (31, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 2, 'нейротехнологии и когнитивные науки');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (32, 'Всероссийская междисциплинарная олимпиада школьников 8-11 класса «Национальная технологическая олимпиада»', null, 2, 'ядерные технологии');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (33, 'Всероссийская олимпиада по агрогенетике для школьников старших классов «Иннагрика»', null, 1, 'аграрная генетика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (34, 'Всероссийская олимпиада по искусственному интеллекту', null, 2, 'искусственный интеллект');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (35, 'Всероссийская олимпиада по музыкально-теоретическим дисциплинам для учащихся детских музыкальных школ и детских школ искусств', null, 2, 'теория и история музыки');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (36, 'Всероссийская олимпиада школьников «Высшая проба»', null, 2, 'биология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (37, 'Всероссийская олимпиада школьников «Высшая проба»', null, 2, 'востоковедение');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (38, 'Всероссийская олимпиада школьников «Высшая проба»', null, 2, 'география');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (39, 'Всероссийская олимпиада школьников «Высшая проба»', null, 1, 'дизайн');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (40, 'Всероссийская олимпиада школьников «Высшая проба»', null, 2, 'восточные языки');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (41, 'Всероссийская олимпиада школьников «Высшая проба»', null, 1, 'иностранный язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (42, 'Всероссийская олимпиада школьников «Высшая проба»', null, 1, 'информатика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (43, 'Всероссийская олимпиада школьников «Высшая проба»', null, 2, 'инженерные науки');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (44, 'Всероссийская олимпиада школьников «Высшая проба»', null, 1, 'история');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (45, 'Всероссийская олимпиада школьников «Высшая проба»', null, 2, 'история мировых цивилизаций');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (46, 'Всероссийская олимпиада школьников «Высшая проба»', null, 3, 'анализ данных');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (47, 'Всероссийская олимпиада школьников «Высшая проба»', null, 1, 'культурология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (48, 'Всероссийская олимпиада школьников «Высшая проба»', null, 1, 'филология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (49, 'Всероссийская олимпиада школьников «Высшая проба»', null, 1, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (50, 'Всероссийская олимпиада школьников «Высшая проба»', null, 1, 'обществознание');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (51, 'Всероссийская олимпиада школьников «Высшая проба»', null, 2, 'международные отношения');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (52, 'Всероссийская олимпиада школьников «Высшая проба»', null, 1, 'политология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (53, 'Всероссийская олимпиада школьников «Высшая проба»', null, 1, 'право');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (54, 'Всероссийская олимпиада школьников «Высшая проба»', null, 2, 'психология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (55, 'Всероссийская олимпиада школьников «Высшая проба»', null, 2, 'русский язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (56, 'Всероссийская олимпиада школьников «Высшая проба»', null, 1, 'социология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (57, 'Всероссийская олимпиада школьников «Высшая проба»', null, 1, 'журналистика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (58, 'Всероссийская олимпиада школьников «Высшая проба»', null, 2, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (59, 'Всероссийская олимпиада школьников «Высшая проба»', null, 1, 'философия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (60, 'Всероссийская олимпиада школьников «Высшая проба»', null, 2, 'химия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (61, 'Всероссийская олимпиада школьников «Высшая проба»', null, 1, 'финансовая грамотность');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (62, 'Всероссийская олимпиада школьников «Высшая проба»', null, 1, 'экономика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (63, 'Всероссийская олимпиада школьников «Высшая проба»', null, 2, 'основы бизнеса');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (64, 'Всероссийская олимпиада школьников «Миссия выполнима. Твое призвание - финансист!»', null, 3, 'иностранный язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (65, 'Всероссийская олимпиада школьников «Миссия выполнима. Твое призвание - финансист!»', null, 3, 'история');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (66, 'Всероссийская олимпиада школьников «Миссия выполнима. Твое призвание - финансист!»', null, 3, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (67, 'Всероссийская олимпиада школьников «Миссия выполнима. Твое призвание - финансист!»', null, 3, 'обществознание');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (68, 'Всероссийская олимпиада школьников «Миссия выполнима. Твое призвание - финансист!»', null, 3, 'финансовая грамотность');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (69, 'Всероссийская олимпиада школьников «Миссия выполнима. Твое призвание - финансист!»', null, 2, 'экономика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (70, 'Всероссийская олимпиада школьников «Юридические высоты!»', null, 2, 'право');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (71, 'Всероссийская Сеченовская олимпиада школьников', null, 2, 'биология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (72, 'Всероссийская Сеченовская олимпиада школьников', null, 2, 'химия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (73, 'Всероссийская Толстовская олимпиада школьников', null, 3, 'история');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (74, 'Всероссийская Толстовская олимпиада школьников', null, 3, 'литература');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (75, 'Всероссийская Толстовская олимпиада школьников', null, 3, 'право');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (76, 'Всероссийская экономическая олимпиада школьников имени Н.Д. Кондратьева', null, 1, 'экономика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (77, 'Всероссийский конкурс научных работ школьников «Юниор»', null, 3, 'естественные науки');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (78, 'Всероссийский конкурс научных работ школьников «Юниор»', null, 3, 'инженерные науки');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (79, 'Всесибирская открытая олимпиада школьников', null, 2, 'биология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (80, 'Всесибирская открытая олимпиада школьников', null, 1, 'информатика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (81, 'Всесибирская открытая олимпиада школьников', null, 2, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (82, 'Всесибирская открытая олимпиада школьников', null, 2, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (83, 'Всесибирская открытая олимпиада школьников', null, 1, 'химия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (84, 'Вузовско-академическая олимпиада по информатике', null, 1, 'информатика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (85, 'Герценовская олимпиада школьников', null, 2, 'география');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (86, 'Герценовская олимпиада школьников', null, 1, 'иностранный язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (87, 'Герценовская олимпиада школьников', null, 3, 'образование и педагогические науки');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (88, 'Городская открытая олимпиада школьников по физике', null, 2, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (89, 'Инженерная олимпиада школьников', null, 1, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (90, 'Интернет-олимпиада школьников по физике', null, 2, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (91, 'Кутафинская олимпиада школьников по праву', null, 1, 'право');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (92, 'Междисциплинарная олимпиада школьников имени В.И. Вернадского', null, 1, 'гуманитарные и социальные науки');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (93, 'Международная Менделеевская Олимпиада по химии', null, 1, 'химия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (94, 'Международная олимпиада «Innopolis Open»', null, 2, 'информатика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (95, 'Международная олимпиада «Innopolis Open»', null, 2, 'информационная безопасность');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (96, 'Международная олимпиада «Innopolis Open»', null, 3, 'робототехника');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (97, 'Международная олимпиада «Innopolis Open»', null, 2, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (98, 'Международная олимпиада по финансовой безопасности', null, 1, 'финансовая безопасность');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (99, 'Международная олимпиада школьников «Искусство графики»', null, 1, 'графический дизайн');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (100, 'Международная олимпиада школьников «Искусство графики»', null, 1, 'рисунок');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (101, 'Международная олимпиада школьников Уральского федерального университета «Изумруд»', null, 3, 'история');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (102, 'Международная олимпиада школьников Уральского федерального университета «Изумруд»', null, 3, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (103, 'Международная олимпиада школьников Уральского федерального университета «Изумруд»', null, 3, 'обществознание');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (104, 'Международная олимпиада школьников Уральского федерального университета «Изумруд»', null, 3, 'русский язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (105, 'Международная олимпиада школьников Уральского федерального университета «Изумруд»', null, 3, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (106, 'Международная олимпиада школьников Уральского федерального университета «Изумруд»', null, 3, 'химия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (107, 'Межрегиональная олимпиада по праву «ФЕМИДА»', null, 2, 'право');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (108, 'Межрегиональная олимпиада школьников «Архитектура и искусство» по комплексу предметов (рисунок, композиция)', null, 1, 'искусство');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (109, 'Межрегиональная олимпиада школьников «Будущие исследователи - будущее науки»', null, 3, 'биология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (110, 'Межрегиональная олимпиада школьников «Будущие исследователи - будущее науки»', null, 2, 'история');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (111, 'Межрегиональная олимпиада школьников «Будущие исследователи - будущее науки»', null, 3, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (112, 'Межрегиональная олимпиада школьников «Будущие исследователи - будущее науки»', null, 3, 'русский язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (113, 'Межрегиональная олимпиада школьников «Будущие исследователи - будущее науки»', null, 2, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (114, 'Межрегиональная олимпиада школьников «Будущие исследователи - будущее науки»', null, 2, 'химия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (115, 'Межрегиональная олимпиада школьников «Евразийская лингвистическая олимпиада»', null, 1, 'иностранный язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (116, 'Межрегиональная олимпиада школьников имени В.Е. Татлина', null, 1, 'графика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (117, 'Межрегиональная олимпиада школьников имени В.Е. Татлина', null, 1, 'композиция');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (118, 'Межрегиональная олимпиада школьников имени В.Е. Татлина', null, 1, 'рисунок');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (119, 'Межрегиональная олимпиада школьников имени И.Я. Верченко', null, 2, 'компьютерная безопасность');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (120, 'Межрегиональная олимпиада школьников имени И.Я. Верченко', null, 2, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (121, 'Межрегиональная олимпиада школьников на базе ведомственных образовательных организаций', null, 3, 'иностранный язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (122, 'Межрегиональная олимпиада школьников на базе ведомственных образовательных организаций', null, 3, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (123, 'Межрегиональная олимпиада школьников на базе ведомственных образовательных организаций', null, 3, 'обществознание');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (124, 'Межрегиональная олимпиада школьников на базе ведомственных образовательных организаций', null, 3, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (125, 'Межрегиональные предметные олимпиады федерального государственного автономного образовательного учреждения высшего образования «Казанский (Приволжский) федеральный университет»', null, 3, 'биология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (126, 'Межрегиональные предметные олимпиады федерального государственного автономного образовательного учреждения высшего образования «Казанский (Приволжский) федеральный университет»', null, 1, 'дизайн');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (127, 'Межрегиональные предметные олимпиады федерального государственного автономного образовательного учреждения высшего образования «Казанский (Приволжский) федеральный университет»', null, 2, 'иностранный язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (128, 'Межрегиональные предметные олимпиады федерального государственного автономного образовательного учреждения высшего образования «Казанский (Приволжский) федеральный университет»', null, 3, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (129, 'Межрегиональные предметные олимпиады федерального государственного автономного образовательного учреждения высшего образования «Казанский (Приволжский) федеральный университет»', null, 3, 'право');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (130, 'Межрегиональные предметные олимпиады федерального государственного автономного образовательного учреждения высшего образования «Казанский (Приволжский) федеральный университет»', null, 2, 'русский язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (131, 'Межрегиональные предметные олимпиады федерального государственного автономного образовательного учреждения высшего образования «Казанский (Приволжский) федеральный университет»', null, 2, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (132, 'Межрегиональные предметные олимпиады федерального государственного автономного образовательного учреждения высшего образования «Казанский (Приволжский) федеральный университет»', null, 1, 'химия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (133, 'Многопредметная олимпиада «Юные таланты»', null, 1, 'география');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (134, 'Многопредметная олимпиада «Юные таланты»', null, 3, 'геология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (135, 'Многопредметная олимпиада «Юные таланты»', null, 1, 'химия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (136, 'Многопрофильная инженерная олимпиада «Звезда»', null, 3, 'естественные науки');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (137, 'Многопрофильная инженерная олимпиада «Звезда»', null, 2, 'техника и технологии');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (138, 'Московская олимпиада школьников', null, 1, 'астрономия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (139, 'Московская олимпиада школьников', null, 3, 'предпрофессиональная');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (140, 'Московская олимпиада школьников', null, 2, 'генетика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (141, 'Московская олимпиада школьников', null, 1, 'география');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (142, 'Московская олимпиада школьников', null, 1, 'лингвистика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (143, 'Московская олимпиада школьников', null, 1, 'информатика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (144, 'Московская олимпиада школьников', null, 1, 'изобразительное искусство');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (145, 'Московская олимпиада школьников', null, 1, 'история искусств');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (146, 'Московская олимпиада школьников', null, 2, 'история');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (147, 'Московская олимпиада школьников', null, 2, 'вероятность и статистика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (148, 'Московская олимпиада школьников', null, 1, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (149, 'Московская олимпиада школьников', null, 3, 'робототехника');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (150, 'Московская олимпиада школьников', null, 2, 'обществознание');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (151, 'Московская олимпиада школьников', null, 3, 'право');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (152, 'Московская олимпиада школьников', null, 3, 'филология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (153, 'Московская олимпиада школьников', null, 1, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (154, 'Московская олимпиада школьников', null, 1, 'химия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (155, 'Московская олимпиада школьников', null, 3, 'экология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (156, 'Московская олимпиада школьников', null, 3, 'финансовая грамотность');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (157, 'Московская олимпиада школьников', null, 2, 'экономика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (158, 'Московская открытая олимпиада школьников по геологии', null, 1, 'геология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (159, 'Общероссийская олимпиада школьников «Основы православной культуры»', null, 3, 'основы православной культуры');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (160, 'Объединенная межвузовская олимпиада школьников', null, 2, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (161, 'Объединенная межвузовская олимпиада школьников', null, 2, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (162, 'Океан знаний', null, 3, 'обществознание');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (163, 'Океан знаний', null, 2, 'русский язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (164, 'Олимпиада Курчатов', null, 2, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (165, 'Олимпиада Курчатов', null, 2, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (166, 'Олимпиада МГИМО МИД России для школьников', null, 2, 'гуманитарные и социальные науки');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (167, 'Олимпиада по архитектуре СПбГАСУ', null, 2, 'рисунок и архитектурная композиция');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (168, 'Олимпиада по комплексу предметов «Культура и искусство»', null, 1, 'академический рисунок, живопись, композиция, история искусства и культуры');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (169, 'Олимпиада по комплексу предметов «Культура и искусство»', null, 1, 'технический рисунок и декоративная композиция');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (170, 'Олимпиада РГГУ для школьников', null, 2, 'иностранный язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (171, 'Олимпиада РГГУ для школьников', null, 2, 'история');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (172, 'Олимпиада РГГУ для школьников', null, 1, 'литература');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (173, 'Олимпиада РГГУ для школьников', null, 3, 'обществознание');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (174, 'Олимпиада РГГУ для школьников', null, 2, 'русский язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (175, 'Олимпиада школьников «Гранит науки»', null, 3, 'информатика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (176, 'Олимпиада школьников «Ломоносов»', null, 3, 'генетика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (177, 'Олимпиада школьников «Ломоносов»', null, 2, 'экология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (178, 'Олимпиада школьников «Ломоносов»', null, 1, 'биология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (179, 'Олимпиада школьников «Ломоносов»', null, 1, 'география');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (180, 'Олимпиада школьников «Ломоносов»', null, 1, 'иностранный язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (181, 'Олимпиада школьников «Ломоносов»', null, 2, 'информатика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (182, 'Олимпиада школьников «Ломоносов»', null, 1, 'история');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (183, 'Олимпиада школьников «Ломоносов»', null, 1, 'международные отношения и глобалистика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (184, 'Олимпиада школьников «Ломоносов»', null, 2, 'политология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (185, 'Олимпиада школьников «Ломоносов»', null, 1, 'основы российской государственности');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (186, 'Олимпиада школьников «Ломоносов»', null, 1, 'литература');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (187, 'Олимпиада школьников «Ломоносов»', null, 1, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (188, 'Олимпиада школьников «Ломоносов»', null, 2, 'космонавтика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (189, 'Олимпиада школьников «Ломоносов»', null, 2, 'механика и математическое моделирование');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (190, 'Олимпиада школьников «Ломоносов»', null, 2, 'робототехника');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (191, 'Олимпиада школьников «Ломоносов»', null, 1, 'высокие технологии');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (192, 'Олимпиада школьников «Ломоносов»', null, 1, 'геология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (193, 'Олимпиада школьников «Ломоносов»', null, 1, 'обществознание');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (194, 'Олимпиада школьников «Ломоносов»', null, 1, 'психология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (195, 'Олимпиада школьников «Ломоносов»', null, 1, 'русский язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (196, 'Олимпиада школьников «Ломоносов»', null, 1, 'журналистика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (197, 'Олимпиада школьников «Ломоносов»', null, 1, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (198, 'Олимпиада школьников «Ломоносов»', null, 2, 'религиоведение');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (199, 'Олимпиада школьников «Ломоносов»', null, 1, 'философия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (200, 'Олимпиада школьников «Ломоносов»', null, 3, 'фундаментальная медицина');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (201, 'Олимпиада школьников «Ломоносов»', null, 1, 'химия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (202, 'Олимпиада школьников «Ломоносов»', null, 2, 'инженерные науки');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (203, 'Олимпиада школьников «Ломоносов»', null, 1, 'право');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (204, 'Олимпиада школьников «Надежда энергетики»', null, 3, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (205, 'Олимпиада школьников «Надежда энергетики»', null, 3, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (206, 'Олимпиада школьников «Покори Воробьевы горы!»', null, 2, 'география');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (207, 'Олимпиада школьников «Покори Воробьевы горы!»', null, 1, 'иностранный язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (208, 'Олимпиада школьников «Покори Воробьевы горы!»', null, 1, 'история');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (209, 'Олимпиада школьников «Покори Воробьевы горы!»', null, 1, 'литература');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (210, 'Олимпиада школьников «Покори Воробьевы горы!»', null, 1, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (211, 'Олимпиада школьников «Покори Воробьевы горы!»', null, 1, 'обществознание');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (212, 'Олимпиада школьников «Покори Воробьевы горы!»', null, 1, 'журналистика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (213, 'Олимпиада школьников «Покори Воробьевы горы!»', null, 1, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (214, 'Олимпиада школьников «Робофест»', null, 2, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (215, 'Олимпиада школьников «Физтех»', null, 2, 'биология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (216, 'Олимпиада школьников «Физтех»', null, 2, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (217, 'Олимпиада школьников «Физтех»', null, 2, 'научно-технический');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (218, 'Олимпиада школьников «Физтех»', null, 3, 'инженерное дело');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (219, 'Олимпиада школьников «Физтех»', null, 1, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (220, 'Олимпиада школьников «Шаг в будущее»', null, 2, 'информатика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (221, 'Олимпиада школьников «Шаг в будущее»', null, 2, 'инженерное дело');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (222, 'Олимпиада школьников «Шаг в будущее»', null, 3, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (223, 'Олимпиада школьников «Шаг в будущее»', null, 3, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (224, 'Олимпиада школьников «Шаг в будущее»', null, 3, 'компьютерное моделирование и графика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (225, 'Олимпиада школьников по информатике и программированию', null, 1, 'информатика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (226, 'Олимпиада школьников по программированию «ТехноКубок»', null, 2, 'информатика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (227, 'Олимпиада школьников по химии в ФГБОУ ВО ПСПбГМУ им. И. П. Павлова Минздрава России', null, 2, 'химия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (228, 'Олимпиада школьников по экономике в рамках международного экономического фестиваля школьников «Сибириада. Шаг в мечту»', null, 2, 'экономика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (229, 'Олимпиада школьников Российской академии народного хозяйства и государственной службы при Президенте Российской Федерации', null, 3, 'иностранный язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (230, 'Олимпиада школьников Российской академии народного хозяйства и государственной службы при Президенте Российской Федерации', null, 2, 'история');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (231, 'Олимпиада школьников Российской академии народного хозяйства и государственной службы при Президенте Российской Федерации', null, 2, 'обществознание');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (232, 'Олимпиада школьников Российской академии народного хозяйства и государственной службы при Президенте Российской Федерации', null, 2, 'политология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (233, 'Олимпиада школьников Российской академии народного хозяйства и государственной службы при Президенте Российской Федерации', null, 2, 'журналистика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (234, 'Олимпиада школьников Российской академии народного хозяйства и государственной службы при Президенте Российской Федерации', null, 3, 'финансовая грамотность');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (235, 'Олимпиада школьников Российской академии народного хозяйства и государственной службы при Президенте Российской Федерации', null, 2, 'экономика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (236, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 3, 'инженерные системы');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (237, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 1, 'биология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (238, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 1, 'география');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (239, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 1, 'иностранный язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (240, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 1, 'филология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (241, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 1, 'информатика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (242, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 1, 'история');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (243, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 1, 'медицина');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (244, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 1, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (245, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 3, 'математическое моделирование и искусственный интеллект');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (246, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 1, 'обществознание');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (247, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 2, 'гуманитарные и социальные науки');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (248, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 2, 'международные отношения');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (249, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 2, 'политология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (250, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 1, 'право');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (251, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 3, 'психология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (252, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 1, 'журналистика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (253, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 1, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (254, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 2, 'философия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (255, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 1, 'химия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (256, 'Олимпиада школьников Санкт-Петербургского государственного университета', null, 2, 'экономика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (257, 'Олимпиада школьников федерального государственного бюджетного образовательного учреждения высшего образования «Всероссийский государственный университет юстиции (РПА Минюста России)» «В мир права»', null, 2, 'право');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (258, 'Олимпиада Юношеской математической школы', null, 2, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (259, 'Открытая межвузовская олимпиада школьников Сибирского федерального округа «Будущее Сибири»', null, 2, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (260, 'Открытая межвузовская олимпиада школьников Сибирского федерального округа «Будущее Сибири»', null, 2, 'химия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (261, 'Открытая олимпиада Северо-Кавказского федерального университета среди учащихся образовательных организаций «45 параллель»', null, 2, 'география');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (262, 'Открытая олимпиада школьников', null, 1, 'информатика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (263, 'Открытая олимпиада школьников', null, 3, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (264, 'Открытая олимпиада школьников', null, 3, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (265, 'Открытая олимпиада школьников по программированию', null, 1, 'информатика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (266, 'Открытая олимпиада школьников по программированию «Когнитивные технологии»', null, 2, 'информатика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (267, 'Открытая региональная межвузовская олимпиада школьников (ОРМО) с международным участием', null, 3, 'география');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (268, 'Открытая региональная межвузовская олимпиада школьников (ОРМО) с международным участием', null, 3, 'история');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (269, 'Открытая региональная межвузовская олимпиада школьников (ОРМО) с международным участием', null, 2, 'литература');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (270, 'Открытая региональная межвузовская олимпиада школьников (ОРМО) с международным участием', null, 3, 'русский язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (271, 'Открытая региональная межвузовская олимпиада школьников (ОРМО) с международным участием', null, 3, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (272, 'Открытая химическая олимпиада', null, 3, 'химия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (273, 'Отраслевая олимпиада школьников «Газпром»', null, 2, 'информационные и коммуникационные технологии');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (274, 'Отраслевая олимпиада школьников «Газпром»', null, 3, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (275, 'Отраслевая олимпиада школьников «Газпром»', null, 3, 'инженерное дело');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (276, 'Отраслевая олимпиада школьников «Газпром»', null, 3, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (277, 'Отраслевая олимпиада школьников «Газпром»', null, 3, 'химия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (278, 'Отраслевая физико-математическая олимпиада школьников «Росатом»', null, 2, 'информатика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (279, 'Отраслевая физико-математическая олимпиада школьников «Росатом»', null, 2, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (280, 'Отраслевая физико-математическая олимпиада школьников «Росатом»', null, 1, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (281, 'Пироговская олимпиада для школьников по химии и биологии', null, 2, 'биология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (282, 'Пироговская олимпиада для школьников по химии и биологии', null, 3, 'химия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (283, 'Плехановская олимпиада школьников', null, 3, 'иностранный язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (284, 'Плехановская олимпиада школьников', null, 3, 'финансовая грамотность');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (285, 'Плехановская олимпиада школьников', null, 3, 'экономика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (286, 'Плехановская олимпиада школьников', null, 2, 'русский язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (287, 'Региональный конкурс школьников Челябинского университетского образовательного округа', null, 3, 'иностранный язык');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (288, 'Региональный конкурс школьников Челябинского университетского образовательного округа', null, 3, 'обществознание');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (289, 'Санкт-Петербургская астрономическая олимпиада', null, 1, 'астрономия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (290, 'Санкт-Петербургская олимпиада школьников', null, 1, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (291, 'Санкт-Петербургская олимпиада школьников', null, 1, 'химия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (292, 'Северо-Восточная олимпиада школьников', null, 3, 'родные языки');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (293, 'Северо-Восточная олимпиада школьников', null, 3, 'филология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (294, 'Сибирская межрегиональная олимпиада школьников «Архитектурно-дизайнерское творчество»', null, 3, 'архитектура, изобразительные и прикладные виды искусств');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (295, 'Строгановская олимпиада', null, 1, 'рисунок, живопись, скульптура, дизайн');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (296, 'Твой путь в настоящую науку', null, 3, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (297, 'Телевизионная гуманитарная олимпиада школьников «Умницы и умники»', null, 1, 'гуманитарные и социальные науки');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (298, 'Турнир городов', null, 1, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (299, 'Турнир имени М.В. Ломоносова', null, 3, 'астрономия и науки о земле');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (300, 'Турнир имени М.В. Ломоносова', null, 3, 'биология');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (301, 'Турнир имени М.В. Ломоносова', null, 2, 'история');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (302, 'Турнир имени М.В. Ломоносова', null, 2, 'литература');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (303, 'Турнир имени М.В. Ломоносова', null, 2, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (304, 'Турнир имени М.В. Ломоносова', null, 2, 'лингвистика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (305, 'Турнир имени М.В. Ломоносова', null, 2, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (306, 'Турнир имени М.В. Ломоносова', null, 3, 'химия');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (307, 'Университетская олимпиада школьников «Бельчонок»', null, 2, 'информатика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (308, 'Университетская олимпиада школьников «Бельчонок»', null, 3, 'математика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (309, 'Университетская олимпиада школьников «Бельчонок»', null, 3, 'физика');
INSERT INTO olympguide.olympiad (olympiad_id, name, description, level, profile) VALUES (310, 'Университетская олимпиада школьников «Бельчонок»', null, 2, 'химия');
